### ISSUE TITLE
iOS 报错 EasyRTSP_Init err -1

### ISSUE THREAD

**Issue by wangguoming0** [EasyDSS/EasyPlayer-RTSP-iOS#4]
EasyRTSP_Init err -1 句柄创建失败  期待您的答复

**Comment by everyu** [comment]
> EasyRTSP_Init err -1 句柄创建失败 期待您的答复

兄台解决了吗？我也遇到了这个问题。

**Comment by 277oscar** [comment]
key过期了，更新下代码就行
